_format_version: '3.0'
_transform: true

services:
  - name: squads
    url: http://squads-service:8080/squads
    routes:
      - name: get_squads
        paths:
          - /squads
        methods:
          - GET
      - name: create_squad
        paths:
          - /squads
        methods:
          - POST
  - name: subscriptions
    url: http://subscriptions-service:8080/subscriptions
    routes:
      - name: get_subscriptions
        paths:
          - /subscriptions
        methods:
          - GET
      - name: create_subscription
        paths:
          - /subscriptions
        methods:
          - POST
