_format_version: '3.0'
_transform: true

services:
  - name: squads
    host: squads-service
    port: 8080
    protocol: http
    routes:
      - name: get_all_squads
        paths:
          - /squads
        methods:
          - GET
      - name: create_squad
        paths:
          - /squads
        methods:
          - POST
