_format_version: '3.0'
_transform: true

services:
  - name: squads
    url: http://squads-service:8080/squads
    routes:
      - name: get_all_squads
        paths:
          - /squads
        methods:
          - GET
      - name: create_squad
        paths:
          - /squads
        methods:
          - POST
