volumes:
  heimdall-dynamodb-data:
    driver: local

networks:
  heimdall-network:
    external: false

services:
  # ---
  # Shared
  # ---
  heimdall-dynamodb:
    container_name: heimdall-dynamodb
    image: "amazon/dynamodb-local:latest"
    volumes:
      - "heimdall-dynamodb-data:/home/dynamodblocal/data"
    networks:
      - heimdall-network
  api-gateway:
    container_name: api-gateway
    image: kong/kong-gateway:3.4-debian
    volumes:
      - './infra/kong/:/kong/declarative'
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      SQUAD_APP_PORT: ${SQUAD_APP_PORT}
    networks:
      - heimdall-network

  # ---
  # Squads
  # ---
  squads-service:
    container_name: squads-service
    image: 10.43.102.250:3000/heimdall/squads-service:latest
    environment:
      DYNAMODB_HOST: ${DYNAMODB_HOST}
      DYNAMODB_PORT: ${DYNAMODB_PORT}
      DYNAMODB_URL: ${DYNAMODB_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      APP_HOST: ${SQUAD_APP_HOST}
      APP_PORT: ${SQUAD_APP_PORT}
    depends_on:
      - heimdall-dynamodb
    networks:
      - heimdall-network
